name: Build and Deploy LaTeX Projects with TikZ Support

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore TeX Live cache
        id: cache-texlive
        uses: actions/cache@v3
        with:
          path: /opt/texlive
          key: texlive-2025-full

      - name: Install TeX Live manually if cache not found
        if: steps.cache-texlive.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full

      - name: Add TeX Live to PATH
        run: echo "/usr/bin" >> $GITHUB_PATH

      - name: Create tex4ht TikZ config file
        run: echo 'Preamble{"\\def\\pgfsysdriver{pgfsys-tex4ht.def}"}' > tikz.cfg

      - name: Convert .tex files to HTML with TikZ support
        run: |
          mkdir -p _converted
          for d in */ ; do
            if compgen -G "$d"*.tex > /dev/null; then
              texfile=$(basename "$d"*.tex)
              name="${texfile%.tex}"
              mkdir -p "_converted/$d"
              cp tikz.cfg "$d"
              make4ht -u -f html5 -c tikz.cfg "$d/$texfile" "mathjax,svg" --shell-escape
              mv "$name.html" "_converted/$d/" || true
            fi
          done

      - name: Generate index.html
        run: |
          echo '<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Index</title>
          <style>
            body { font-family: sans-serif; background: #f8f9fa; padding: 2rem; }
            .card { background: white; border-radius: 12px; box-shadow: 0 4px 10px rgba(0,0,0,0.1); padding: 1rem; margin: 1rem; display: inline-block; width: 280px; text-align: center; }
            .card a { text-decoration: none; color: #007acc; font-weight: bold; }
          </style></head><body><h1>Available Projects</h1>' > index.html
          for dir in _converted/*/ ; do
            projname=$(basename "$dir")
            link=$(find "$dir" -name "*.html" | head -n 1)
            if [ -f "$link" ]; then
              echo "<div class='card'><h2>$projname</h2><a href='${link#_converted/}'>View Site</a></div>" >> index.html
            fi
          done
          echo '</body></html>' >> index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
