name: Build and Deploy LaTeX Projects with TikZ Support

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup manual TeX Live installation
        run: |
          mkdir -p texlive && cd texlive
          wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
          tar -xzf install-tl-unx.tar.gz --strip-components=1
          echo "selected_scheme scheme-full" > texlive.profile
          ./install-tl --profile=texlive.profile --no-interaction
          echo "::set-output name=texlive_installed::true"
        id: setup-texlive

      - name: Add TeX Live to PATH
        run: |
          echo "${GITHUB_WORKSPACE}/texlive/bin/x86_64-linux" >> $GITHUB_PATH

      - name: Convert .tex files to HTML with TikZ support
        run: |
          mkdir -p _converted
          for d in */ ; do
            if compgen -G "$d"*.tex > /dev/null; then
              texfile=$(basename "$d"*.tex)
              name="${texfile%.tex}"
              mkdir -p "_converted/$d"
              sed -i 's/\\documentclass/\\def\\pgfsysdriver{pgfsys-tex4ht.def}\\documentclass/' "$d/$texfile"
              cd "$d"
              make4ht -u -f html5 "$texfile" "mathjax,svg" --shell-escape
              cd ..
              cp -r "$d"/*.html "$d"/*.svg "$d"/*.css "$d"/*.js "$d"/*.png "$d"/*.jpg "$d"/*.gif "$d"/*.xml "$d"/*.idv "$d"/*.lg "$d"/*.tmp "$d"/*.xref _converted/"$d" 2>/dev/null || true
            fi
          done

      - name: Generate index.html
        run: |
          echo '<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Index</title>
          <style>
            body { font-family: sans-serif; background: #f8f9fa; padding: 2rem; }
            .card { background: white; border-radius: 12px; box-shadow: 0 4px 10px rgba(0,0,0,0.1); padding: 1rem; margin: 1rem; display: inline-block; width: 280px; text-align: center; }
            .card a { text-decoration: none; color: #007acc; font-weight: bold; }
          </style></head><body><h1>Available Projects</h1>' > index.html
          for dir in _converted/*/ ; do
            projname=$(basename "$dir")
            if [ -f "$dir"/*.html ]; then
              echo "<div class='card'><h2>$projname</h2><a href='_converted/$projname/'>View Site</a></div>" >> index.html
            fi
          done
          echo '</body></html>' >> index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true
